name: graphrag-experiments CI Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      
      - name: Lint with Pylint
        run: |
          python -m pylint --rcfile=.pylintrc .
